name: markdown-lint
on: ## pull request
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          config: '.markdownlint.yml'
          globs: '**/*.md'
          fix: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: lint markdown files'
          branch: ${{ github.head_ref }}