name: markdown-lint
on: ## pull request
  pull_request:
    paths:
      - '*.md'
      - 'docs/*.md'
      - 'docs/**/*.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@v15